from pynput.keyboard import Key, KeyCode

START_KEY = Key.f6
STOP_KEY = Key.f7

FORWARD_TWEAK_KEY = "]"
BACKWARD_TWEAK_KEY = "\\"
DOUBLE_FORWARD_TWEAK_KEY = "["
DOUBLE_BACKWARD_TWEAK_KEY = "'"
CLEANUP_RUN_KEY = "."
